name: Package LeoCAD

on:
  push:
    branches:
      - master

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download release binary
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "leozide/leocad"
        latest: true
        fileName: "*.AppImage"

    - name: Install dependencies
      run: sudo apt-get install -y ruby
        

    - name: Create Debian package
      run: |
        bash build.sh

