name: Package LeoCAD

on:
  push:
    branches:
      - master

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download release binary
      id: download_release
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "leozide/leocad"
        latest: true
        fileName: "*.AppImage"

    - name: Install fpm
      run: sudo gem install fpm && fpm --version
        
    - name: Create Debian package
      run: |
        fpm \
          -s dir -t deb \
          -p LeoCAD-${{steps.download_release.outputs.tag_name}}-1-amd64.deb \
          --name LeoCAD \
          --license agpl3 \
          --version ${{steps.download_release.outputs.tag_name}} \
          --architecture amd64 \
          --depends bash --depends libfuse2 \
          --description "A CAD application for creating virtual LEGO models." \
          --url "https://www.leocad.org/" \
          --maintainer "debilin <croninlucio@gmail.com>" \
          --after-install ./afterinstall.sh \
            ${{ fromJson(steps.download_release.outputs.downloaded_files)[0] }}=/usr/local/bin/leocad

